- name: add nginx repository
  apt_repository:
    repo: ppa:nginx/stable
    state: present
- name: apt update cache and install nginx
  apt:
    update_cache: yes
    name: nginx
    state: present
- name: copy nginx default site configuration
  copy:
    src: nginx_default_site_conf
    dest: /etc/nginx/sites-available/default
    force: yes
  notify: reload nginx
- name: link nginx default site configuration to sites-enabled
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    force: yes
    state: link
- name: ufw allow port 80
  ufw:
    rule: allow
    port: 80
    proto: tcp
